export const CATEGORIES = {
  functional: "Functional",
  core_hip: "Core / Hip",
};

export const EXERCISES = [
  {
    id: "squat_overhead_db_press",
    name: "Squat with overhead dumbbell press",
    category: "functional",
    description: "Squat paired with overhead dumbbell press.",
    defaultWeight: 12.5,
    defaultReps: null,
    defaultDurationSeconds: null,
    measurementTypes: ["weight", "notes"],
    primaryMetric: "weight",
    sideMode: "none",
    sortOrder: 1,
  },
  {
    id: "press_outs",
    name: "Medicine ball / dumbbell press-outs",
    category: "functional",
    description: "Press ball or dumbbell straight out.",
    defaultWeight: 10,
    defaultReps: null,
    defaultDurationSeconds: null,
    measurementTypes: ["weight", "notes"],
    primaryMetric: "weight",
    sideMode: "none",
    sortOrder: 2,
  },
  {
    id: "walking_lunges_trunk_rotation_press_out",
    name: "Walking lunges with trunk rotation and ball press-out",
    category: "functional",
    description: "Rotate trunk and press ball out during lunges.",
    defaultWeight: 10,
    defaultReps: null,
    defaultDurationSeconds: null,
    measurementTypes: ["weight", "notes"],
    primaryMetric: "weight",
    sideMode: "none",
    sortOrder: 3,
  },
  {
    id: "pulley_lifts",
    name: "Pulley lifts",
    category: "functional",
    description: "Pulley set low. Stand in deep squat, lift up and away, then return.",
    defaultWeight: 14,
    defaultReps: null,
    defaultDurationSeconds: null,
    measurementTypes: ["weight", "notes"],
    primaryMetric: "weight",
    sideMode: "none",
    sortOrder: 4,
  },
  {
    id: "pulley_chops",
    name: "Pulley chops",
    category: "functional",
    description: "Pulley set high. Half-kneel and pull down/across body.",
    defaultWeight: 20.5,
    defaultReps: null,
    defaultDurationSeconds: null,
    measurementTypes: ["weight", "notes"],
    primaryMetric: "weight",
    sideMode: "each_side",
    sortOrder: 5,
  },
  {
    id: "half_kneeling_rise_overhead_raise_balance",
    name: "Half-kneeling rise to opposite-arm overhead dumbbell raise and single-leg balance",
    category: "functional",
    description:
      "Weight is held in the opposite hand from the forward leg. Rise into single-leg stance with the weight in the arm on the side where the leg lifts into the air.",
    defaultWeight: 12.5,
    defaultReps: null,
    defaultDurationSeconds: null,
    measurementTypes: ["weight", "notes"],
    primaryMetric: "weight",
    sideMode: "each_side",
    sortOrder: 6,
  },
  {
    id: "farmers_carry_side",
    name: "Farmer's carry at side",
    category: "functional",
    description: "Carry weight at the side. Track weight only.",
    defaultWeight: 35,
    defaultReps: null,
    defaultDurationSeconds: null,
    measurementTypes: ["weight", "notes"],
    primaryMetric: "weight",
    sideMode: "none",
    sortOrder: 7,
  },
  {
    id: "farmers_overhead_carry",
    name: "Farmer's overhead carry",
    category: "functional",
    description: "Carry weight overhead. Track weight only.",
    defaultWeight: 17.5,
    defaultReps: null,
    defaultDurationSeconds: null,
    measurementTypes: ["weight", "notes"],
    primaryMetric: "weight",
    sideMode: "none",
    sortOrder: 8,
  },
  {
    id: "lateral_band_monster_walks_press",
    name: "Lateral band walks or monster walks with ball press-out or overhead press",
    category: "core_hip",
    description: "Can be performed with ball press-out or ball overhead.",
    defaultWeight: 10,
    defaultReps: null,
    defaultDurationSeconds: null,
    measurementTypes: ["weight", "notes"],
    primaryMetric: "weight",
    sideMode: "none",
    sortOrder: 1,
  },
  {
    id: "front_plank_alternating_legs",
    name: "Front plank, alternating legs",
    category: "core_hip",
    description: "Track total duration.",
    defaultWeight: null,
    defaultReps: null,
    defaultDurationSeconds: 60,
    measurementTypes: ["duration", "notes"],
    primaryMetric: "duration",
    sideMode: "none",
    sortOrder: 2,
  },
  {
    id: "sidelying_hip_abduction_rainbows",
    name: "Sidelying hip abduction rainbows",
    category: "core_hip",
    description: "Top hip lifts into a rainbow arc forward and back. Keep hip stacked.",
    defaultWeight: null,
    defaultReps: 15,
    defaultDurationSeconds: null,
    measurementTypes: ["reps", "notes"],
    primaryMetric: "reps",
    sideMode: "each_side",
    sortOrder: 3,
  },
  {
    id: "bent_knee_sit_up",
    name: "Bent knee sit up",
    category: "core_hip",
    description: "Curl up from a bent-knee position. Track total reps.",
    defaultWeight: null,
    defaultReps: 10,
    defaultDurationSeconds: null,
    measurementTypes: ["reps", "notes"],
    primaryMetric: "reps",
    sideMode: "none",
    sortOrder: 4,
  },
  {
    id: "single_leg_glute_bridge_hold",
    name: "Single-leg glute bridge hold",
    category: "core_hip",
    description: "Track hold time.",
    defaultWeight: null,
    defaultReps: null,
    defaultDurationSeconds: 45,
    measurementTypes: ["duration", "notes"],
    primaryMetric: "duration",
    sideMode: "none",
    sortOrder: 5,
  },
  {
    id: "back_single_leg_scissor_drop",
    name: "Back single-leg scissor drop",
    category: "core_hip",
    description: "Can add upper body crunch for increased upper abdominal activation.",
    defaultWeight: null,
    defaultReps: 15,
    defaultDurationSeconds: null,
    measurementTypes: ["reps", "notes"],
    primaryMetric: "reps",
    sideMode: "each_side",
    sortOrder: 6,
  },
  {
    id: "ball_back_extension",
    name: "Ball back extension",
    category: "core_hip",
    description: "Track total reps.",
    defaultWeight: null,
    defaultReps: 30,
    defaultDurationSeconds: null,
    measurementTypes: ["reps", "notes"],
    primaryMetric: "reps",
    sideMode: "none",
    sortOrder: 7,
  },
  {
    id: "ball_side_flexion",
    name: "Ball side flexion",
    category: "core_hip",
    description: "Track reps per side or each-side value.",
    defaultWeight: null,
    defaultReps: 10,
    defaultDurationSeconds: null,
    measurementTypes: ["reps", "notes"],
    primaryMetric: "reps",
    sideMode: "each_side",
    sortOrder: 8,
  },
];

export function categoryLabel(category) {
  return CATEGORIES[category] || category;
}

export function getExercise(id) {
  return EXERCISES.find((exercise) => exercise.id === id) || null;
}

export function exercisesForCategory(category) {
  return EXERCISES.filter((exercise) => exercise.category === category).sort(
    (a, b) => a.sortOrder - b.sortOrder,
  );
}

export function isValidCategory(category) {
  return Object.prototype.hasOwnProperty.call(CATEGORIES, category);
}
